#!/bin/bash

echo "Please enter user name : "
read USERNAME #the value entered will be attached to the USERNAME variable.  

echo "User name is : $USERNAME"

echo "Please enter user name : "
read -s USERNAME #the value entered will be attached to the USERNAME variable. 
# read -s : this is used to hide the entered content 

echo "User name is : $USERNAME"